# Generated by Django 4.1.3 on 2022-11-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restrant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='restraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restrant.restraunt'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='restraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restrant.restraunt'),
        ),
    ]
