# Generated by Django 4.1.3 on 2022-11-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0006_restraunt_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='restraunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.restraunt'),
        ),
    ]
